INSERT INTO `dolgozok` (`d_id`, `d_nev`, `a_id`, `t_id`, `p_id`) VALUES
(NULL, 'Nádori Péter', '1','6','5'),					
		(NULL, 'Mendi Gyula Lórántné', '1','6','5'),
		(NULL, 'Bozsik Enikő ', '1','6','5'),
		(NULL, 'Gazsi Henrietta', '1','6','5'),
		(NULL, 'Bánfi Ernőné', '1','6','5'),
		(NULL, 'Balog Klára', '1','6','5'),
		(NULL, 'Márkus Anna', '1','6','5'),
		(NULL, 'Czibula Tibor', '1','6','5'),
		(NULL, 'Sallai Jánosné', '1','6','5'),
		(NULL, 'Szilágyi Panni', '1','6','5'),
		(NULL, 'Sponga Gáborné', '1','6','5'),
		(NULL, 'Zsabka Erzsébet Krisztina', '1','6','5'),
		(NULL, 'Schleicher Istvánné', '1','6','5'),
		(NULL, 'Lakatos Tamásné', '1','6','5'),
		(NULL, 'Petrikné Oláh Márta', '1','6','5'),
		(NULL, 'Szekeresné Király Gyöngyi ', '1','6','5'),
		(NULL, 'Rafael Ágoston ', '1','6','5'),
		(NULL, 'Szabó József Sándor', ' 1','6','5'),
		(NULL, 'Bálint Márk ', '1','6','5'),
		(NULL, 'Lisócki Norbert Zakariás ', '1','6','5'),
		(NULL, 'Mohácsi Kálmán', '1','6','5'),
		(NULL, 'Bene Cintia', '1','6','5'),
		(NULL, 'Gál Levente', '1','6','5'),
		(NULL, 'Mohácsi József', '1','6','5'),
		(NULL, 'Gombkötő Csaba', '1','6','6'),
		(NULL, 'Udvaros Edina', '1','8','18'), 	
		(NULL, 'Kovács Mónika', '1','8','18'),
		(NULL, 'Durai Tamás', '1','8','18'),
		(NULL, 'Babos Tamás', '1','8','18'),
		(NULL, 'Juhász László', '1','8','18'),
		(NULL, 'Hideghéti Anita', '1','8','19'),
		(NULL, 'Durai László', '1','8','19'),
		(NULL, 'Mezsgyán Richárd', '1','8','20'),
		(NULL, 'Somogyi László Junior', '1','8','21'),
		(NULL, 'Opóczki Tamás', '1','8','21'),
		(NULL, 'Parancs Dániel', '1','8','21'),
		(NULL, 'Domonkos Gabriella Petra', '1','8','22'),
		(NULL, 'Lakatos Helga', '1','8','22'),
		(NULL, 'Pál Teréz', '1','8','23'),
		(NULL, 'Horváth Teréz', '1','8','23'),
		(NULL, 'Orosz Ella', '1','8','23'),
		(NULL, 'Nyitrai Rozália', '1','8','23'),
		(NULL, 'Bíró Nóra', '1','8','23'),
		(NULL, 'Vörös Kálmán', '1','8','24'),
		(NULL, 'Rizmajer Richárd', '1','8','24'),
		(NULL, 'Csürge Zoltán', '1','8','24'),
		(NULL, 'Rézműves Márk', '1','8','25'),
		(NULL, 'Fejes Gergő', '1','8','26'),
		(NULL, 'Szabó Norbert', '1','8','26'),
		(NULL, 'Sponga Gáborné', '1','8','27'),
		(NULL, 'Bólya István', '1','9','28'),
		(NULL, 'Buzás Attila', '1','9','29'),
		(NULL, 'Bor Gábor Károly', '1','9','29'),
		(NULL, 'Fórizs Olivér', '1','9','29'),
		(NULL, 'Fekete Sándor', '1','9','29'),
		(NULL, 'Szebényi Zsolt', '1','9','29'),
		(NULL, 'Petrok János Viktor', '1','9','29'),
		(NULL, 'Fazakas Mihály', '1','9','29'),
		(NULL, 'Oláh Arnold', '1','9','29'),
		(NULL, 'Hajdu Dániel', '1','9','29'),
		(NULL, 'Kurunczi Renátó', '1','9','29'),
		(NULL, 'Laczkó Sándor', '1','9','29'),
		(NULL, 'Rutterschmidt Zoltánné', '1','9','29'),
		(NULL, 'Nagy Rudolf', '1','9','29'),
		(NULL, 'Kökény József', '1','9','29'),
		(NULL, 'Csébi Róbert István', '1','9','29'),
		(NULL, 'Horváth Sándor', '1','9','29'),
		(NULL, 'Keresztény Flóra', '1','9','30'),
		(NULL, 'Farkas István Gáborné', '1','9','30'),
		(NULL, 'Balog Marianna', '1','9','30'),
		(NULL, 'Krizsán Károlyné', '1','9','30'),
		(NULL, 'Gulyás Olívia Odett', '1','9','30'),
		(NULL, 'Pupos Ildikó', '1','9','30'),
		(NULL, 'Deli Nóra', '1','9','30'),
		(NULL, 'Lánczos Ferencné', '1','9','30'),
		(NULL, 'Rutterschmidt Zoltánné', '1','9','30'),
		(NULL, 'Theil Viktória', '1','9','30'),
		(NULL, 'Jakab Éva', '1','9','30'),
		(NULL, 'Major Hajnalka', '1','9','30'),
		(NULL, 'Pölcz Tiborné Hajnalka', '1','9','30'),
		(NULL, 'Kökény Szabina', '1','9','30'),
		(NULL, 'Vargáné Varga Anita', '1','9','30'),
		(NULL, 'Kovács Alíz', '1','9','30'),
		(NULL, 'Szluka Attiláné Erika', '1','9','31'),
		(NULL, 'Nagy Péterné 10.12.', '1','9','31'),
		(NULL, 'Molnár Nanda Mercedesz', '1','9','32'),
		(NULL, 'Andó Gábor 10.12.', '1','9','32'),
		(NULL, 'Rézműves Márk', '1','9','32'),
		(NULL, 'Ódór Balázs', '1','9','32'),
		(NULL, 'Lakatos Venczel József', '1','9','32'),
		(NULL, 'Balogh Mónika', '1','9','32'),
		(NULL, 'Tukacs Vanda', '1','1','33'),
		(NULL, 'Rostné Butnaru Luminita', '1','1','33'),
		(NULL, 'Oláh Dániel', '1','1','33'),
		(NULL, 'Domonyi Sándor', '1','1','33'),
		(NULL, 'Tóth László Mihályné', '1','1','33'),
		(NULL, 'Polyák Mónika', '1','1','34'),
		(NULL, 'Szabó Nikolett', '1','1','34'),
		(NULL, 'Újvári Izabella', '1','1','34'),
		(NULL, 'Ménich Adrienn Katalin', '1','1','34'),
		(NULL, 'Belinszki Anita Julianna', '1','1','35'),
		(NULL, 'Márton Piroska', '1','1','35'),
		(NULL, 'Rigó Beatrix', '1','1','35'),
		(NULL, 'Hajdúné Pethő Zsuzsanna 10.12.', '1','1','35'),
		(NULL, 'Kohán Szilvia', '1','1','35'),
		(NULL, 'Harmatiné Gazsik Éva', '1','1','35'),
		(NULL, 'Harazin Anett', '1','1','35'),
		(NULL, 'Juhász Judit', '1','1','35'),
		(NULL, 'Volenszki Anett', '1','1','36'),
		(NULL, 'Kocsis Brigitta', '1','1','36'),
		(NULL, 'Herczéné Szapek Emese', '1','1','37'),
		(NULL, 'Dinnyés Csaba', '1','1','38'),
		(NULL, 'Bravik Erika Zsuzsanna', '1','1','39'),
		(NULL, 'Géró László Ferencné', '1','1','39'),
		(NULL, 'Fentor János Ádám', '1','1','39'),
		(NULL, 'Bednárik Erzsébet', '1','1','39'),
		(NULL, 'Fentor Dominik János', '1','1','39'),
		(NULL, 'Aszódiné Csorba Edina', '1','1','39'),
		(NULL, 'Márton Viktória', '1','1','39'),
		(NULL, 'Rafael Alexandra Erzsébet', '1','1','39'),
		(NULL, 'Makai Andrea', '1','1','39'),
		(NULL, 'Miskolcziné Kőszegi Klára', '1','1','40'),
		(NULL, 'Csikósné Szabó Mónik', '1','1','40'),
		(NULL, 'Kovácsné Pálesz Nikolett', ' 1','1','40'),
		(NULL, 'Peregovits Kálmánné', '1','1','41'),
		(NULL, 'Garajszki Mária', '1','1','41'),
		(NULL, 'Lajter Lászlóné', '1','1','41'),
		(NULL, 'Varga János', '1','1','41'),
		(NULL, 'Szabó Róbert', '1','1','41'),
		(NULL, 'Varsányi Tamás', '1','1','42'),
		(NULL, 'Surányi Zsolt', '1','1','42'),
		(NULL, 'Koleff Sándor Miklós', '1','1','42'),
		(NULL, 'Sziklási Lilla Ildikó', '1','1','43'),
		(NULL, 'Urbán Krisztián', '1','1','44'),
		(NULL, 'Rusznyák Dániel', '1','1','44'),
		(NULL, 'Rabné Szerényi Zita', '1','1','44'),
		(NULL, 'Mohácsi Zsolt', '1','1','44'),
		(NULL, 'Molnár Ádám', '1','1','44'),