INSERT INTO `pozicio` (`p_id`, `p_elnevezes`, `t_id`) VALUES 
(NULL, 'ELŐGYÁRTÁS', '6'),
(NULL, 'SORTÖLTÉS', '6'),
(NULL, 'JETELÉS', '7'),
(NULL, 'BELSŐ JET ', '7'),
(NULL, 'DÚSÍTÁS', '7'),
(NULL, 'CSÖVEZÉS', '7'),
(NULL, 'KERETEZÉS', '7'),
(NULL, 'MOTOROZÁS', '7'),
(NULL, 'ELEKTROMOS SZERELÉS', '7'),
(NULL, 'FELRAKÓ', '7'),
(NULL, 'CSOMAGOLÁS', '7'),
(NULL, 'KÁD LÁBAZÁS', '7'),
(NULL, 'KÁD SZERELÉS', '7'),
(NULL, 'Szerelő', '8'),
(NULL, 'WM', '8'),
(NULL, 'elektromos', '8'),
(NULL, 'burkolás', '8'),
(NULL, 'csomagolás', '8'),
(NULL, 'FRP', '8'),
(NULL, 'fúró', '8'),
(NULL, 'targoncás/kézi anyagmozgató', '8'),
(NULL, 'vákuum', '8'),
(NULL, 'előkészítő', '8'),
(NULL, 'SAROK GYÁRTÁS', '9'),
(NULL, 'BURKOLÁS', '9'),
(NULL, 'CSOMAGOLÁS', '9'),
(NULL, 'TAKARÍTÓK', '9'),
(NULL, 'ANYAG-MOZGATÁS, PÁNTOLÁS', '9'),
(NULL, 'Sorközi ellenőrzés', '1'),
(NULL, 'Csomagolás ellenőrzés', '1'),
(NULL, 'Test ellenőrzés', '1'),
(NULL, 'Swim spa ellenőrzés', '1'),
(NULL, 'Extruder - Tető ellenőrzés', '1'),
(NULL, 'Kád', '1'),
(NULL, 'Vég MEO', '1'),
(NULL, 'Puffer', '1'),
(NULL, 'PORSZÍVÓ', '1'),
(NULL, 'MEO ELEKTROMOS', '1'),
(NULL, 'REWORK', '1'),
(NULL, 'FÉNYEZŐ', '1'),
(NULL, 'PU', '3'),
(NULL, 'FÚRÓ ROBOT', '3'), 
(NULL, 'VÁGÓ' , '3'),
(NULL, 'VÁKUUM' , '3'),
(NULL, 'TÁLCA VÁKUUM', '3'),
(NULL, 'KÉZI FÚRÓ' , '3'),
(NULL, 'FELRAKÓ', '3'),
(NULL, 'LAPSZABÁSZAT', '4'),
(NULL, 'KERET SZABÁSZAT', '4'),
(NULL, 'KERETEZÉS', '4'),
(NULL, 'BURKOLAT KÉSZÍTŐ', '4'),
(NULL, 'SZIGETELŐ', '4'),
(NULL, 'SAROK GYÁRTÁS', '4'),
(NULL, 'ElŐKÉSZÍTŐ', '4'),
(NULL, 'DÍSZKERETEZÉS', '4'),
(NULL, 'HUNGAROCELL', '10'),
(NULL, 'SZABÁSZAT', '10'),
(NULL, 'VARRODA', '10'),
(NULL, 'SZITÁZÓ', '10'),
(NULL, 'TÖMÉSZET', '10'),
(NULL, 'EXTRUDER', '11'),
(NULL, 'DOMBORNYOMÓ - SZÁLCSISZOLÓ', '11'),
(NULL, 'KÁD VÁKUUM', '11'),
(NULL, 'HEGESZTŐ', '12'),
(NULL, 'DARABOLÓS', '12');